spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/open-api/user-service/**
          filters:
            - RewritePath=/open-api/user-service/(?<segment>.*), /api/user-service/$\{segment}
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/open-api/task-service/**
          filters:
            - RewritePath=/open-api/task-service/(?<segment>.*), /api/task-service/$\{segment}
chemical:
  property:
    filter:
      black-path:
        black-path-list:
          - /open-api/task-service/
          - /open-api/user-service/
        white-path-list:
          - /open-api/user-service/login
          - /open-api/user-service/register
          - /open-api/user-service/reset/mail-code
          - /open-api/user-service/reset
